[sources.strava]
access_token  = "1dd2b5bab8ef6010140ae886bc4958096ddd8377"
refresh_token = "42966a69466c13f175b72c920144f59804b5a152"
client_id     = "133027"
client_secret = "66dff8a3147b8ede632a89c96f0c238472bb8261"
